var MAPPING_CAMT053_MT940 = {
  mtType: 'MT940',

  fields: [
    {
      isoPath: 'Stmt/Id',
      isoName: 'Statement Identification',
      mtTag: '20',
      mtName: 'Transaction Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO statement ID truncated to MT max 16 chars.'
    },
    {
      isoPath: 'Stmt/Acct/Id',
      isoName: 'Account Identification',
      mtTag: '25',
      mtName: 'Account Identification',
      transform: 'accountIdReverse',
      status: 'clean',
      notes: 'IBAN or proprietary account ID passed through.'
    },
    {
      isoPath: 'Stmt/ElctrncSeqNb',
      isoName: 'Electronic Sequence Number',
      mtTag: '28C',
      mtName: 'Statement Number / Sequence Number',
      transform: 'buildStatementNumber',
      status: 'transformed',
      notes: 'ElctrncSeqNb/LglSeqNb combined to statement/sequence format.'
    },
    {
      isoPath: 'Stmt/Bal[OPBD]',
      isoName: 'Opening Booked Balance',
      mtTag: '60F',
      mtName: 'Opening Balance (First)',
      transform: 'balanceReverse',
      status: 'transformed',
      notes: 'ISO Bal with OPBD type mapped to :60F: with D/C + date + currency + amount.'
    },
    {
      isoPath: 'Stmt/Ntry',
      isoName: 'Entry',
      mtTag: '61',
      mtName: 'Statement Line',
      transform: 'entryToStatementLine',
      status: 'transformed',
      notes: 'Each Ntry becomes a :61: line. Significant data loss in structured fields.'
    },
    {
      isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/AddtlTxInf',
      isoName: 'Additional Transaction Information',
      mtTag: '86',
      mtName: 'Information to Account Owner',
      transform: 'splitLines65',
      status: 'transformed',
      notes: 'Additional info split to 6×65 char lines for :86:.'
    },
    {
      isoPath: 'Stmt/Bal[CLBD]',
      isoName: 'Closing Booked Balance',
      mtTag: '62F',
      mtName: 'Closing Balance (Booked)',
      transform: 'balanceReverse',
      status: 'transformed',
      notes: 'ISO Bal with CLBD type mapped to :62F:.'
    },
    {
      isoPath: 'Stmt/Bal[CLAV]',
      isoName: 'Closing Available Balance',
      mtTag: '64',
      mtName: 'Closing Available Balance',
      transform: 'balanceReverse',
      status: 'transformed',
      notes: 'ISO Bal with CLAV type mapped to :64:.'
    },
    {
      isoPath: 'Stmt/Bal[FWAV]',
      isoName: 'Forward Available Balance',
      mtTag: '65',
      mtName: 'Forward Available Balance',
      transform: 'balanceReverse',
      status: 'transformed',
      notes: 'ISO Bal with FWAV type mapped to :65:. Repeating.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: O940 + timestamps + BICs' }
  ],

  dataLoss: [
    { isoPath: 'Stmt/FrToDt', description: 'Date range has no MT940 equivalent — dropped' },
    { isoPath: 'Stmt/Ntry/Sts/Cd', description: 'Entry status (BOOK/PDNG) cannot be represented — dropped' },
    { isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/RltdPties', description: 'Structured party details cannot be represented in MT940 — dropped' },
    { isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/RltdAgts', description: 'Agent BICs cannot be represented in :61: — dropped' },
    { isoPath: 'Stmt/Ntry/BkTxCd/Domn', description: 'Structured domain/family codes collapsed to 4-char type — lossy' },
    { isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/RmtInf/Strd', description: 'Structured remittance dropped — only unstructured fits :86:' },
    { isoPath: 'SplmtryData', description: 'Supplementary data has no MT equivalent — dropped' }
  ],

  valueMaps: {},

  // Engine metadata
  direction: 'iso-to-mt',
  sourceType: 'camt.053',
  targetType: 'MT940',
  isStatement: true,

  isoRootElement: 'BkToCstmrStmt',
  isoTxPath: 'Stmt',

  envelope: {
    block1Bic: { fixed: 'BANKUS33XXXX' },
    block2Type: '940',
    block2Style: 'output'
  },

  mtFieldOrder: ['20', '25', '28C', '60F', '61', '86', '62F', '64', '65'],

  balanceMappings: [
    { isoType: 'OPBD', mtTag: '60F' },
    { isoType: 'CLBD', mtTag: '62F' },
    { isoType: 'CLAV', mtTag: '64' },
    { isoType: 'FWAV', mtTag: '65' }
  ]
};
