var MAPPING_CAMT054_MT900 = {
  mtType: 'MT900',

  fields: [
    {
      isoPath: 'Ntfctn/Id',
      isoName: 'Notification Identification',
      mtTag: '20',
      mtName: 'Transaction Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO notification ID truncated to MT max 16 chars.'
    },
    {
      isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/Refs/AcctSvcrRef',
      isoName: 'Account Servicer Reference',
      mtTag: '21',
      mtName: 'Related Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'Servicer reference truncated to 16 chars for :21:.'
    },
    {
      isoPath: 'Ntfctn/Acct/Id',
      isoName: 'Account Identification',
      mtTag: '25',
      mtName: 'Account Identification',
      transform: 'accountIdReverse',
      status: 'clean',
      notes: 'IBAN or proprietary account ID passed through.'
    },
    {
      isoPath: 'Ntfctn/Ntry/Amt',
      isoName: 'Entry Amount',
      mtTag: '32A',
      mtName: 'Value Date / Currency / Amount',
      transform: 'buildTag32A',
      status: 'transformed',
      notes: 'Combines ValDt (date), Ccy attribute (currency), and value (amount) into compound :32A: field.'
    },
    {
      isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/RltdAgts/DbtrAgt/FinInstnId/BICFI',
      isoName: 'Debtor Agent BIC',
      mtTag: '52A',
      mtName: 'Ordering Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: O900 + timestamps + BICs' }
  ],

  dataLoss: [
    { isoPath: 'Ntfctn/Ntry/Sts/Cd', description: 'Entry status (BOOK/PDNG) cannot be represented in MT900 — dropped' },
    { isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/RltdPties', description: 'Structured party details cannot be represented — dropped' },
    { isoPath: 'Ntfctn/Ntry/BkTxCd/Domn', description: 'Structured domain/family codes have no MT900 equivalent — dropped' },
    { isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/RmtInf', description: 'Remittance information cannot be represented in MT900 — dropped' }
  ],

  valueMaps: {},

  // Engine metadata
  direction: 'iso-to-mt',
  sourceType: 'camt.054',
  targetType: 'MT900',
  isNotification: true,

  isoRootElement: 'BkToCstmrDbtCdtNtfctn',
  isoTxPath: 'Ntfctn',

  envelope: {
    block1Bic: { fixed: 'CHASUS33XXXX' },
    block2Type: '900',
    block2Style: 'output'
  },

  mtFieldOrder: ['20', '21', '25', '32A', '52A']
};
