var MAPPING_CAMT052_MT942 = {
  mtType: 'MT942',

  fields: [
    {
      isoPath: 'Rpt/Id',
      isoName: 'Report Identification',
      mtTag: '20',
      mtName: 'Transaction Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO report ID truncated to MT max 16 chars.'
    },
    {
      isoPath: 'Rpt/Acct/Id',
      isoName: 'Account Identification',
      mtTag: '25',
      mtName: 'Account Identification',
      transform: 'accountIdReverse',
      status: 'clean',
      notes: 'IBAN or proprietary account ID passed through.'
    },
    {
      isoPath: 'Rpt/ElctrncSeqNb',
      isoName: 'Electronic Sequence Number',
      mtTag: '28C',
      mtName: 'Statement Number / Sequence Number',
      transform: 'buildStatementNumber',
      status: 'transformed',
      notes: 'ElctrncSeqNb/LglSeqNb combined to statement/sequence format.'
    },
    {
      isoPath: 'Rpt/Ntry',
      isoName: 'Entry',
      mtTag: '61',
      mtName: 'Statement Line',
      transform: 'entryToStatementLine',
      status: 'transformed',
      notes: 'Each Ntry becomes a :61: line. Significant data loss in structured fields.'
    },
    {
      isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/AddtlTxInf',
      isoName: 'Additional Transaction Information',
      mtTag: '86',
      mtName: 'Information to Account Owner',
      transform: 'splitLines65',
      status: 'transformed',
      notes: 'Additional info split to 6×65 char lines for :86:.'
    },
    {
      isoPath: 'Rpt/TxsSummry/TtlDbtNtries',
      isoName: 'Total Debit Entries',
      mtTag: '90D',
      mtName: 'Number and Sum of Debit Entries',
      transform: 'summaryEntriesReverse',
      status: 'transformed',
      notes: 'NbOfNtries and Sum combined into :90D: count + currency + amount format.'
    },
    {
      isoPath: 'Rpt/TxsSummry/TtlCdtNtries',
      isoName: 'Total Credit Entries',
      mtTag: '90C',
      mtName: 'Number and Sum of Credit Entries',
      transform: 'summaryEntriesReverse',
      status: 'transformed',
      notes: 'NbOfNtries and Sum combined into :90C: count + currency + amount format.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: O942 + timestamps + BICs' },
    { mtField: ':34F: Floor Notification Amount', description: 'Generated as zero amount in account currency' },
    { mtField: ':13D: Date/Time Indication', description: 'Generated from Rpt/CreDtTm' }
  ],

  dataLoss: [
    { isoPath: 'Rpt/FrToDt', description: 'Report period has no MT942 equivalent — dropped' },
    { isoPath: 'Rpt/Ntry/Sts/Cd', description: 'Entry status (BOOK/PDNG) cannot be represented — dropped' },
    { isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/RltdPties', description: 'Structured party details cannot be represented — dropped' },
    { isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/RltdAgts', description: 'Agent BICs cannot be represented in :61: — dropped' },
    { isoPath: 'Rpt/Ntry/BkTxCd/Domn', description: 'Structured domain/family codes collapsed to 4-char type — lossy' },
    { isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/RmtInf/Strd', description: 'Structured remittance dropped — only unstructured fits :86:' }
  ],

  valueMaps: {},

  // Engine metadata
  direction: 'iso-to-mt',
  sourceType: 'camt.052',
  targetType: 'MT942',
  isStatement: true,

  isoRootElement: 'BkToCstmrAcctRpt',
  isoTxPath: 'Rpt',

  envelope: {
    block1Bic: { fixed: 'BANKUS33XXXX' },
    block2Type: '942',
    block2Style: 'output'
  },

  mtFieldOrder: ['20', '25', '28C', '34F', '13D', '61', '86', '90D', '90C']
};
