var MAPPING_MT103RETURN_PACS004 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:pacs.004.001.09',
  rootElement: 'PmtRtr',

  fields: [
    {
      mtTag: '20',
      mtName: 'Transaction Reference',
      isoPath: 'TxInf/RtrId',
      isoName: 'Return Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping. The return message reference becomes the return ID.'
    },
    {
      mtTag: '21',
      mtName: 'Related Reference',
      isoPath: 'TxInf/OrgnlEndToEndId',
      isoName: 'Original End to End Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Related reference links back to the original payment\'s end-to-end ID.'
    },
    {
      mtTag: '32A',
      mtName: 'Value Date / Currency / Amount',
      isoPath: 'TxInf/RtrdIntrBkSttlmAmt',
      isoName: 'Returned Interbank Settlement Amount',
      transform: 'decode32A',
      status: 'transformed',
      notes: 'Compound field split: date→IntrBkSttlmDt, currency→Ccy attribute, amount→element value.'
    },
    {
      mtTag: '50K',
      mtName: 'Ordering Customer (Name & Address)',
      isoPath: 'TxInf/OrgnlTxRef/Dbtr',
      isoName: 'Original Debtor',
      transform: 'partyToDebtor',
      status: 'transformed',
      notes: 'In return context, the ordering customer maps to the original debtor reference. Address: unstructured to structured is lossy.'
    },
    {
      mtTag: '52A',
      mtName: 'Ordering Institution',
      isoPath: 'TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/BICFI',
      isoName: 'Original Debtor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping to original debtor agent.'
    },
    {
      mtTag: '57A',
      mtName: 'Account With Institution',
      isoPath: 'TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Original Creditor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping to original creditor agent.'
    },
    {
      mtTag: '59',
      mtName: 'Beneficiary Customer',
      isoPath: 'TxInf/OrgnlTxRef/Cdtr',
      isoName: 'Original Creditor',
      transform: 'partyToCreditor',
      status: 'transformed',
      notes: 'In return context, the beneficiary maps to the original creditor reference.'
    },
    {
      mtTag: '72',
      mtName: 'Sender to Receiver Information',
      isoPath: 'TxInf/RtrRsnInf/AddtlInf',
      isoName: 'Return Reason Additional Information',
      transform: 'joinLines',
      status: 'transformed',
      notes: 'Free text return reason. Coded reasons (e.g. /REJT/) mapped to RtrRsnInf/Rsn/Cd where possible.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/MsgId', description: 'Auto-generated message ID' },
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'GrpHdr/NbOfTxs', description: 'Always "1" for single return' },
    { isoPath: 'GrpHdr/SttlmInf/SttlmMtd', description: 'Defaults to CLRG' },
    { isoPath: 'TxInf/OrgnlGrpInf/OrgnlMsgNmId', description: 'Set to pacs.008.001.08 (assumed original)' }
  ],

  dataGaps: [
    { isoPath: 'TxInf/OrgnlGrpInf/OrgnlMsgId', description: 'Original message ID not available in MT103 return — generated' },
    { isoPath: 'TxInf/RtrRsnInf/Rsn/Cd', description: 'Structured return reason code requires parsing from :72: coded words' },
    { isoPath: 'TxInf/OrgnlTxRef/Dbtr/Id/OrgId/LEI', description: 'LEI not available in MT format' }
  ],

  valueMaps: {
    returnReason: { '/REJT/': 'AM04', '/RETN/': 'AC04', '/RTYP/': 'MS03' }
  },

  // Engine metadata
  direction: 'mt-to-iso',
  sourceType: 'MT103RET',
  targetType: 'pacs.004',

  txElement: 'TxInf',

  fixedElements: [
    { isoPath: 'GrpHdr/MsgId', value: '$MSGID' },
    { isoPath: 'GrpHdr/CreDtTm', value: '$NOW' },
    { isoPath: 'GrpHdr/NbOfTxs', value: '1' },
    { isoPath: 'GrpHdr/SttlmInf/SttlmMtd', value: 'CLRG' }
  ],

  attributes: {
    'TxInf/RtrdIntrBkSttlmAmt': { attr: 'Ccy', from: 'currency' }
  },

  elementOrder: [
    'GrpHdr', 'TxInf'
  ]
};
