var MAPPING_MT104_PAIN008 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:pain.008.001.08',
  rootElement: 'CstmrDrctDbtInitn',

  fields: [
    {
      mtTag: '20',
      mtName: 'Sender\'s Reference',
      isoPath: 'PmtInf/PmtInfId',
      isoName: 'Payment Information Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping. Batch reference becomes payment information ID.'
    },
    {
      mtTag: '23E',
      mtName: 'Instruction Code',
      isoPath: null,
      isoName: null,
      transform: 'drop',
      status: 'gap',
      notes: 'MT104 instruction code (OTHR, SDVA, etc.) has no direct pain.008 equivalent.'
    },
    {
      mtTag: '30',
      mtName: 'Requested Execution Date',
      isoPath: 'PmtInf/ReqdColltnDt/Dt',
      isoName: 'Requested Collection Date',
      transform: 'dateOnly',
      status: 'transformed',
      notes: 'MT date YYMMDD converted to ISO date YYYY-MM-DD. Execution date→collection date in DD context.'
    },
    {
      mtTag: '51A',
      mtName: 'Sending Institution',
      isoPath: 'PmtInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Sending institution maps to creditor agent in direct debit context.'
    },
    {
      mtTag: '50K',
      mtName: 'Ordering Customer (Creditor)',
      isoPath: 'PmtInf/Cdtr',
      isoName: 'Creditor',
      transform: 'partyToCreditor',
      status: 'transformed',
      notes: 'In direct debit, the ordering customer is the creditor (who initiates the collection). Account→CdtrAcct, Name→Cdtr/Nm.'
    },
    {
      mtTag: '21',
      mtName: 'Transaction Reference',
      isoPath: 'PmtInf/DrctDbtTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Individual debit reference within the batch.'
    },
    {
      mtTag: '32B',
      mtName: 'Currency / Transaction Amount',
      isoPath: 'PmtInf/DrctDbtTxInf/InstdAmt',
      isoName: 'Instructed Amount',
      transform: 'decode32B',
      status: 'transformed',
      notes: 'Currency→Ccy attribute, amount→element value.'
    },
    {
      mtTag: '57A',
      mtName: 'Account With Institution',
      isoPath: 'PmtInf/DrctDbtTxInf/DbtrAgt/FinInstnId/BICFI',
      isoName: 'Debtor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'In direct debit, account with institution is the debtor\'s bank.'
    },
    {
      mtTag: '59',
      mtName: 'Beneficiary Customer (Debtor)',
      isoPath: 'PmtInf/DrctDbtTxInf/Dbtr',
      isoName: 'Debtor',
      transform: 'partyToDebtor',
      status: 'transformed',
      notes: 'In direct debit, the "beneficiary" (party being debited) is the debtor. Account→DbtrAcct, Name→Dbtr/Nm.'
    },
    {
      mtTag: '70',
      mtName: 'Remittance Information',
      isoPath: 'PmtInf/DrctDbtTxInf/RmtInf/Ustrd',
      isoName: 'Unstructured Remittance',
      transform: 'joinLines',
      status: 'transformed',
      notes: 'MT multi-line (4×35) joined into single unstructured string.'
    },
    {
      mtTag: '71A',
      mtName: 'Details of Charges',
      isoPath: 'PmtInf/ChrgBr',
      isoName: 'Charge Bearer',
      transform: 'chargeBearer',
      status: 'transformed',
      notes: 'SHA→SHAR, OUR→DEBT, BEN→CRED.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/MsgId', description: 'Auto-generated message ID' },
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'GrpHdr/NbOfTxs', description: 'Count of transactions in batch' },
    { isoPath: 'GrpHdr/CtrlSum', description: 'Sum of all transaction amounts' },
    { isoPath: 'GrpHdr/InitgPty/Nm', description: 'Initiating party name (from :50K:)' },
    { isoPath: 'PmtInf/PmtMtd', description: 'Always DD for direct debit initiation' },
    { isoPath: 'PmtInf/NbOfTxs', description: 'Count of transactions in this payment block' }
  ],

  dataGaps: [
    { isoPath: 'PmtInf/Cdtr/Id/OrgId/LEI', description: 'LEI not available in MT format' },
    { isoPath: 'PmtInf/DrctDbtTxInf/DrctDbtTx/MndtRltdInf', description: 'Mandate information not available in MT104' },
    { isoPath: 'PmtInf/DrctDbtTxInf/Purp/Cd', description: 'Purpose code not available in MT104' },
    { isoPath: 'PmtInf/DrctDbtTxInf/RmtInf/Strd', description: 'Structured remittance not available in MT104' }
  ],

  valueMaps: {
    chargeBearer: { 'SHA': 'SHAR', 'OUR': 'DEBT', 'BEN': 'CRED' }
  },

  // Engine metadata
  direction: 'mt-to-iso',
  sourceType: 'MT104',
  targetType: 'pain.008',

  txElement: 'PmtInf',

  fixedElements: [
    { isoPath: 'GrpHdr/MsgId', value: '$MSGID' },
    { isoPath: 'GrpHdr/CreDtTm', value: '$NOW' },
    { isoPath: 'GrpHdr/NbOfTxs', value: '1' }
  ],

  attributes: {
    'PmtInf/DrctDbtTxInf/InstdAmt': { attr: 'Ccy', from: 'currency' }
  },

  elementOrder: [
    'GrpHdr', 'PmtInf'
  ]
};
