var MAPPING_MT101_PAIN001 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:pain.001.001.09',
  rootElement: 'CstmrCdtTrfInitn',

  fields: [
    {
      mtTag: '20',
      mtName: 'Sender\'s Reference',
      isoPath: 'PmtInf/PmtInfId',
      isoName: 'Payment Information Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping. Batch reference becomes payment information ID.'
    },
    {
      mtTag: '28D',
      mtName: 'Message Index / Total',
      isoPath: null,
      isoName: null,
      transform: 'drop',
      status: 'gap',
      notes: 'Message sequencing (1/3, 2/3 etc.) has no pain.001 equivalent — handled at transport level.'
    },
    {
      mtTag: '30',
      mtName: 'Requested Execution Date',
      isoPath: 'PmtInf/ReqdExctnDt/Dt',
      isoName: 'Requested Execution Date',
      transform: 'dateOnly',
      status: 'transformed',
      notes: 'MT date YYMMDD converted to ISO date YYYY-MM-DD.'
    },
    {
      mtTag: '25',
      mtName: 'Authorisation (Account)',
      isoPath: 'PmtInf/DbtrAcct/Id',
      isoName: 'Debtor Account',
      transform: 'accountId',
      status: 'transformed',
      notes: 'IBAN detection with proprietary fallback.'
    },
    {
      mtTag: '21',
      mtName: 'Transaction Reference',
      isoPath: 'PmtInf/CdtTrfTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Individual payment reference within the batch.'
    },
    {
      mtTag: '32B',
      mtName: 'Currency / Transaction Amount',
      isoPath: 'PmtInf/CdtTrfTxInf/Amt/InstdAmt',
      isoName: 'Instructed Amount',
      transform: 'decode32B',
      status: 'transformed',
      notes: 'Currency→Ccy attribute, amount→element value. MT comma decimal→ISO dot decimal.'
    },
    {
      mtTag: '50K',
      mtName: 'Ordering Customer (Name & Address)',
      isoPath: 'PmtInf/Dbtr',
      isoName: 'Debtor',
      transform: 'partyToDebtor',
      status: 'transformed',
      notes: 'Account→DbtrAcct/Id. Name→Dbtr/Nm. Address lines→Dbtr/PstlAdr (unstructured to structured is lossy).'
    },
    {
      mtTag: '57A',
      mtName: 'Account With Institution',
      isoPath: 'PmtInf/CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      mtTag: '59',
      mtName: 'Beneficiary Customer',
      isoPath: 'PmtInf/CdtTrfTxInf/Cdtr',
      isoName: 'Creditor',
      transform: 'partyToCreditor',
      status: 'transformed',
      notes: 'Account→CdtrAcct, Name→Cdtr/Nm, Address→Cdtr/PstlAdr.'
    },
    {
      mtTag: '70',
      mtName: 'Remittance Information',
      isoPath: 'PmtInf/CdtTrfTxInf/RmtInf/Ustrd',
      isoName: 'Unstructured Remittance',
      transform: 'joinLines',
      status: 'transformed',
      notes: 'MT multi-line (4×35) joined into single unstructured string.'
    },
    {
      mtTag: '71A',
      mtName: 'Details of Charges',
      isoPath: 'PmtInf/ChrgBr',
      isoName: 'Charge Bearer',
      transform: 'chargeBearer',
      status: 'transformed',
      notes: 'SHA→SHAR, OUR→DEBT, BEN→CRED.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/MsgId', description: 'Auto-generated message ID' },
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'GrpHdr/NbOfTxs', description: 'Count of transactions in batch' },
    { isoPath: 'GrpHdr/CtrlSum', description: 'Sum of all transaction amounts' },
    { isoPath: 'GrpHdr/InitgPty/Nm', description: 'Initiating party name (from :50K:)' },
    { isoPath: 'PmtInf/PmtMtd', description: 'Always TRF for credit transfer initiation' },
    { isoPath: 'PmtInf/NbOfTxs', description: 'Count of transactions in this payment block' }
  ],

  dataGaps: [
    { isoPath: 'PmtInf/Dbtr/Id/OrgId/LEI', description: 'LEI not available in MT format' },
    { isoPath: 'PmtInf/CdtTrfTxInf/Purp/Cd', description: 'Purpose code not available in MT101' },
    { isoPath: 'PmtInf/CdtTrfTxInf/RmtInf/Strd', description: 'Structured remittance not available in MT101' }
  ],

  valueMaps: {
    chargeBearer: { 'SHA': 'SHAR', 'OUR': 'DEBT', 'BEN': 'CRED' }
  },

  // Engine metadata
  direction: 'mt-to-iso',
  sourceType: 'MT101',
  targetType: 'pain.001',

  txElement: 'PmtInf',

  fixedElements: [
    { isoPath: 'GrpHdr/MsgId', value: '$MSGID' },
    { isoPath: 'GrpHdr/CreDtTm', value: '$NOW' },
    { isoPath: 'GrpHdr/NbOfTxs', value: '1' }
  ],

  attributes: {
    'PmtInf/CdtTrfTxInf/Amt/InstdAmt': { attr: 'Ccy', from: 'currency' }
  },

  elementOrder: [
    'GrpHdr', 'PmtInf'
  ]
};
