var MAPPING_MT202_PACS009 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:pacs.009.001.08',
  rootElement: 'FICdtTrf',

  fields: [
    {
      mtTag: '20',
      mtName: 'Transaction Reference',
      isoPath: 'CdtTrfTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping. Max 16 chars in MT, max 35 in ISO.'
    },
    {
      mtTag: '21',
      mtName: 'Related Reference',
      isoPath: 'CdtTrfTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Related reference maps to EndToEndId. :20: used as MsgId instead when :21: present.'
    },
    {
      mtTag: '32A',
      mtName: 'Value Date / Currency / Amount',
      isoPath: 'CdtTrfTxInf/IntrBkSttlmAmt',
      isoName: 'Interbank Settlement Amount',
      transform: 'decode32A',
      status: 'transformed',
      notes: 'Compound field split: date→IntrBkSttlmDt, currency→Ccy attribute, amount→element value.'
    },
    {
      mtTag: '52A',
      mtName: 'Ordering Institution',
      isoPath: 'CdtTrfTxInf/Dbtr/FinInstnId/BICFI',
      isoName: 'Debtor Financial Institution BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping. In MT202 all parties are financial institutions.'
    },
    {
      mtTag: '53A',
      mtName: 'Sender Correspondent',
      isoPath: 'CdtTrfTxInf/InstgRmbrsmntAgt/FinInstnId/BICFI',
      isoName: 'Instructing Reimbursement Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Sender correspondent maps to instructing reimbursement agent.'
    },
    {
      mtTag: '54A',
      mtName: 'Receiver Correspondent',
      isoPath: 'CdtTrfTxInf/InstdRmbrsmntAgt/FinInstnId/BICFI',
      isoName: 'Instructed Reimbursement Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Receiver correspondent maps to instructed reimbursement agent.'
    },
    {
      mtTag: '56A',
      mtName: 'Intermediary Institution',
      isoPath: 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/BICFI',
      isoName: 'Intermediary Agent 1 BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      mtTag: '57A',
      mtName: 'Account With Institution',
      isoPath: 'CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Account with institution maps to creditor agent.'
    },
    {
      mtTag: '58A',
      mtName: 'Beneficiary Institution',
      isoPath: 'CdtTrfTxInf/Cdtr/FinInstnId/BICFI',
      isoName: 'Creditor Financial Institution BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Beneficiary institution maps directly to creditor FI.'
    },
    {
      mtTag: '72',
      mtName: 'Sender to Receiver Information',
      isoPath: 'CdtTrfTxInf/InstrForNxtAgt/InstrInf',
      isoName: 'Instruction for Next Agent',
      transform: 'joinLines',
      status: 'transformed',
      notes: 'Free text instruction. Multi-line joined. Coded instructions not mapped to structured equivalents.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/MsgId', description: 'Auto-generated message ID' },
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'GrpHdr/NbOfTxs', description: 'Always "1" for single MT202' },
    { isoPath: 'GrpHdr/SttlmInf/SttlmMtd', description: 'CLRG or COVE based on :53A: presence' },
    { isoPath: 'CdtTrfTxInf/PmtId/InstrId', description: 'Auto-generated instruction ID' }
  ],

  dataGaps: [
    { isoPath: 'CdtTrfTxInf/Dbtr/FinInstnId/LEI', description: 'LEI not available in MT format' },
    { isoPath: 'CdtTrfTxInf/Cdtr/FinInstnId/LEI', description: 'LEI not available in MT format' },
    { isoPath: 'CdtTrfTxInf/Purp/Cd', description: 'Purpose code not available in MT202' }
  ],

  // Engine metadata
  direction: 'mt-to-iso',
  sourceType: 'MT202',
  targetType: 'pacs.009',

  txElement: 'CdtTrfTxInf',

  fixedElements: [
    { isoPath: 'GrpHdr/MsgId', value: '$MSGID' },
    { isoPath: 'GrpHdr/CreDtTm', value: '$NOW' },
    { isoPath: 'GrpHdr/NbOfTxs', value: '1' },
    { isoPath: 'GrpHdr/SttlmInf/SttlmMtd', value: '$STTLM' }
  ],

  attributes: {
    'CdtTrfTxInf/IntrBkSttlmAmt': { attr: 'Ccy', from: 'currency' }
  },

  elementOrder: [
    'GrpHdr', 'CdtTrfTxInf'
  ]
};
