var MAPPING_MT900_CAMT054 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:camt.054.001.08',
  rootElement: 'BkToCstmrDbtCdtNtfctn',

  fields: [
    {
      mtTag: '20',
      mtName: 'Transaction Reference',
      isoPath: 'Ntfctn/Id',
      isoName: 'Notification Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping to notification ID.'
    },
    {
      mtTag: '21',
      mtName: 'Related Reference',
      isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/Refs/AcctSvcrRef',
      isoName: 'Account Servicer Reference',
      transform: 'direct',
      status: 'clean',
      notes: 'Related reference maps to the servicer reference linking back to the original payment.'
    },
    {
      mtTag: '25',
      mtName: 'Account Identification',
      isoPath: 'Ntfctn/Acct/Id',
      isoName: 'Account Identification',
      transform: 'accountId',
      status: 'transformed',
      notes: 'IBAN detection with proprietary fallback. IBAN→IBAN element, other→Othr/Id.'
    },
    {
      mtTag: '32A',
      mtName: 'Value Date / Currency / Amount',
      isoPath: 'Ntfctn/Ntry/Amt',
      isoName: 'Entry Amount',
      transform: 'decode32A',
      status: 'transformed',
      notes: 'Compound field split: date→ValDt, currency→Ccy attribute, amount→element value. D/C indicator set to DBIT for MT900.'
    },
    {
      mtTag: '52A',
      mtName: 'Ordering Institution',
      isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/RltdAgts/DbtrAgt/FinInstnId/BICFI',
      isoName: 'Debtor Agent BIC',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping. Ordering institution maps to debtor agent in notification context.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/MsgId', description: 'Auto-generated message ID' },
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'Ntfctn/CreDtTm', description: 'Notification creation datetime' },
    { isoPath: 'Ntfctn/Ntry/Sts/Cd', description: 'Defaults to BOOK' },
    { isoPath: 'Ntfctn/Ntry/CdtDbtInd', description: 'Set to DBIT for MT900 debit notification' },
    { isoPath: 'Ntfctn/Ntry/BkTxCd/Prtry/Cd', description: 'Defaults to NTRF' }
  ],

  dataGaps: [
    { isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/RltdPties', description: 'Debtor/creditor party details not available in MT900' },
    { isoPath: 'Ntfctn/Ntry/BkTxCd/Domn', description: 'Structured domain/family codes not in MT900' },
    { isoPath: 'Ntfctn/Ntry/NtryDtls/TxDtls/RmtInf', description: 'Remittance information not available in MT900' }
  ],

  // Engine metadata
  direction: 'mt-to-iso',
  sourceType: 'MT900',
  targetType: 'camt.054',

  txElement: 'Ntfctn',
  isNotification: true,

  fixedElements: [
    { isoPath: 'GrpHdr/MsgId', value: '$MSGID' },
    { isoPath: 'GrpHdr/CreDtTm', value: '$NOW' }
  ],

  attributes: {
    'Ntfctn/Ntry/Amt': { attr: 'Ccy', from: 'currency' }
  },

  elementOrder: [
    'GrpHdr', 'Ntfctn'
  ]
};
