var MAPPING_MT942_CAMT052 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:camt.052.001.08',
  rootElement: 'BkToCstmrAcctRpt',

  fields: [
    {
      mtTag: '20',
      mtName: 'Transaction Reference',
      isoPath: 'GrpHdr/MsgId',
      isoName: 'Message Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping to group header message ID.'
    },
    {
      mtTag: '25',
      mtName: 'Account Identification',
      isoPath: 'Rpt/Acct/Id',
      isoName: 'Account Identification',
      transform: 'accountId',
      status: 'transformed',
      notes: 'IBAN detection with proprietary fallback. IBAN→IBAN element, other→Othr/Id.'
    },
    {
      mtTag: '28C',
      mtName: 'Statement Number / Sequence Number',
      isoPath: 'Rpt/ElctrncSeqNb',
      isoName: 'Electronic Sequence Number',
      transform: 'statementNumber',
      status: 'transformed',
      notes: 'Statement/sequence split. Statement number→ElctrncSeqNb, sequence→LglSeqNb.'
    },
    {
      mtTag: '34F',
      mtName: 'Floor Notification Amount',
      isoPath: null,
      isoName: null,
      transform: 'drop',
      status: 'gap',
      notes: 'Floor notification amount has no direct camt.052 equivalent — this is an MT-specific threshold trigger.'
    },
    {
      mtTag: '13D',
      mtName: 'Date/Time Indication',
      isoPath: 'Rpt/CreDtTm',
      isoName: 'Report Creation Date Time',
      transform: 'dateTimeIndication',
      status: 'transformed',
      notes: 'MT date/time with UTC offset converted to ISO datetime format.'
    },
    {
      mtTag: '61',
      mtName: 'Statement Line',
      isoPath: 'Rpt/Ntry',
      isoName: 'Entry',
      transform: 'statementLine',
      status: 'transformed',
      notes: 'Each :61: becomes an Ntry element. Value date, D/C, amount, transaction type extracted. Repeating field.'
    },
    {
      mtTag: '86',
      mtName: 'Information to Account Owner',
      isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/AddtlTxInf',
      isoName: 'Additional Transaction Information',
      transform: 'joinLines',
      status: 'transformed',
      notes: 'Free text per transaction. Each :86: paired with preceding :61:.'
    },
    {
      mtTag: '90D',
      mtName: 'Number and Sum of Debit Entries',
      isoPath: 'Rpt/TxsSummry/TtlDbtNtries',
      isoName: 'Total Debit Entries',
      transform: 'summaryEntries',
      status: 'transformed',
      notes: 'Count and sum of debits. Maps to NbOfNtries and Sum in TtlDbtNtries.'
    },
    {
      mtTag: '90C',
      mtName: 'Number and Sum of Credit Entries',
      isoPath: 'Rpt/TxsSummry/TtlCdtNtries',
      isoName: 'Total Credit Entries',
      transform: 'summaryEntries',
      status: 'transformed',
      notes: 'Count and sum of credits. Maps to NbOfNtries and Sum in TtlCdtNtries.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'Rpt/Id', description: 'Report identification (from :20:)' },
    { isoPath: 'Rpt/Ntry/Sts/Cd', description: 'Defaults to BOOK' }
  ],

  dataGaps: [
    { isoPath: 'Rpt/FrToDt', description: 'Intraday report period not explicit in MT942' },
    { isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/RltdPties', description: 'Debtor/creditor party details not in MT942' },
    { isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/RltdAgts', description: 'Agent BICs not in MT942 :61:' },
    { isoPath: 'Rpt/Ntry/BkTxCd/Domn', description: 'Structured domain/family codes require SWIFT code mapping' },
    { isoPath: 'Rpt/Ntry/NtryDtls/TxDtls/RmtInf/Strd', description: 'Structured remittance not in MT942' }
  ],

  // Engine metadata
  direction: 'mt-to-iso',
  sourceType: 'MT942',
  targetType: 'camt.052',

  txElement: 'Rpt',
  isStatement: true,

  fixedElements: [
    { isoPath: 'GrpHdr/MsgId', value: '$MSGID' },
    { isoPath: 'GrpHdr/CreDtTm', value: '$NOW' }
  ],

  repeatingSection: {
    mtTag: '61',
    pairedTag: '86',
    isoParent: 'Rpt/Ntry'
  }
};
