var MAPPING_MT940_CAMT053 = {
  isoNamespace: 'urn:iso:std:iso:20022:tech:xsd:camt.053.001.08',
  rootElement: 'BkToCstmrStmt',

  fields: [
    {
      mtTag: '20',
      mtName: 'Transaction Reference',
      isoPath: 'GrpHdr/MsgId',
      isoName: 'Message Identification',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct 1:1 mapping to group header message ID.'
    },
    {
      mtTag: '25',
      mtName: 'Account Identification',
      isoPath: 'Stmt/Acct/Id',
      isoName: 'Account Identification',
      transform: 'accountId',
      status: 'transformed',
      notes: 'IBAN detection with proprietary fallback. IBAN→IBAN element, other→Othr/Id.'
    },
    {
      mtTag: '28C',
      mtName: 'Statement Number / Sequence Number',
      isoPath: 'Stmt/ElctrncSeqNb',
      isoName: 'Electronic Sequence Number',
      transform: 'statementNumber',
      status: 'transformed',
      notes: 'Statement/sequence split. Statement number→ElctrncSeqNb, sequence→LglSeqNb.'
    },
    {
      mtTag: '60F',
      mtName: 'Opening Balance (First)',
      isoPath: 'Stmt/Bal[OPBD]',
      isoName: 'Opening Booked Balance',
      transform: 'balance',
      status: 'transformed',
      notes: 'D/C indicator + date + currency + amount mapped to Bal with CdtDbtInd, Dt, Amt Ccy, and Tp/CdOrPrtry/Cd=OPBD.'
    },
    {
      mtTag: '61',
      mtName: 'Statement Line',
      isoPath: 'Stmt/Ntry',
      isoName: 'Entry',
      transform: 'statementLine',
      status: 'transformed',
      notes: 'Each :61: becomes an Ntry element. Value date, D/C, amount, transaction type extracted. Repeating field.'
    },
    {
      mtTag: '86',
      mtName: 'Information to Account Owner',
      isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/AddtlTxInf',
      isoName: 'Additional Transaction Information',
      transform: 'joinLines',
      status: 'transformed',
      notes: 'Free text per transaction. Each :86: paired with preceding :61:.'
    },
    {
      mtTag: '62F',
      mtName: 'Closing Balance (Booked)',
      isoPath: 'Stmt/Bal[CLBD]',
      isoName: 'Closing Booked Balance',
      transform: 'balance',
      status: 'transformed',
      notes: 'Same structure as :60F: but with Tp/CdOrPrtry/Cd=CLBD.'
    },
    {
      mtTag: '64',
      mtName: 'Closing Available Balance',
      isoPath: 'Stmt/Bal[CLAV]',
      isoName: 'Closing Available Balance',
      transform: 'balance',
      status: 'transformed',
      notes: 'Optional. Maps to Bal with Tp/CdOrPrtry/Cd=CLAV.'
    },
    {
      mtTag: '65',
      mtName: 'Forward Available Balance',
      isoPath: 'Stmt/Bal[FWAV]',
      isoName: 'Forward Available Balance',
      transform: 'balance',
      status: 'transformed',
      notes: 'Optional, repeating. Maps to Bal with Tp/CdOrPrtry/Cd=FWAV.'
    }
  ],

  autoGenerated: [
    { isoPath: 'GrpHdr/CreDtTm', description: 'Current ISO datetime' },
    { isoPath: 'Stmt/CreDtTm', description: 'Statement creation datetime' },
    { isoPath: 'Stmt/Id', description: 'Statement identification (from :20:)' }
  ],

  dataGaps: [
    { isoPath: 'Stmt/FrToDt', description: 'Date range not explicit in MT940' },
    { isoPath: 'Stmt/Ntry/Sts/Cd', description: 'Entry status (BOOK/PDNG) not in MT940' },
    { isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/RltdPties', description: 'Debtor/creditor party details not in MT940' },
    { isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/RltdAgts', description: 'Agent BICs not in MT940 :61:' },
    { isoPath: 'Stmt/Ntry/BkTxCd/Domn', description: 'Structured domain/family codes require SWIFT code mapping' },
    { isoPath: 'Stmt/Ntry/NtryDtls/TxDtls/RmtInf/Strd', description: 'Structured remittance not in MT940' }
  ]
};
