var MAPPING_PACS008_MT103 = {
  mtType: 'MT103',

  fields: [
    {
      isoPath: 'CdtTrfTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      mtTag: '20',
      mtName: 'Transaction Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO max 35 chars truncated to MT max 16 chars. Data loss if EndToEndId > 16 characters.'
    },
    {
      isoPath: 'CdtTrfTxInf/IntrBkSttlmAmt',
      isoName: 'Interbank Settlement Amount',
      mtTag: '32A',
      mtName: 'Value Date / Currency / Amount',
      transform: 'buildTag32A',
      status: 'transformed',
      notes: 'Combines IntrBkSttlmDt (date), Ccy attribute (currency), and value (amount) into compound :32A: field. Dot decimal→comma decimal.'
    },
    {
      isoPath: 'CdtTrfTxInf/InstdAmt',
      isoName: 'Instructed Amount',
      mtTag: '33B',
      mtName: 'Currency / Instructed Amount',
      transform: 'buildTag33B',
      status: 'clean',
      notes: 'Ccy attribute + value combined into :33B:.'
    },
    {
      isoPath: 'CdtTrfTxInf/Dbtr',
      isoName: 'Debtor',
      mtTag: '50K',
      mtName: 'Ordering Customer',
      transform: 'debtorToParty',
      status: 'transformed',
      notes: 'Structured ISO address collapsed to 4×35 unstructured lines. IBAN→/account line. Some address detail may be lost.'
    },
    {
      isoPath: 'CdtTrfTxInf/DbtrAgt/FinInstnId/BICFI',
      isoName: 'Debtor Agent BIC',
      mtTag: '52A',
      mtName: 'Ordering Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      mtTag: '57A',
      mtName: 'Account With Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/Cdtr',
      isoName: 'Creditor',
      mtTag: '59',
      mtName: 'Beneficiary Customer',
      transform: 'creditorToParty',
      status: 'transformed',
      notes: 'Same as Debtor but for beneficiary. Structured→unstructured address collapse.'
    },
    {
      isoPath: 'CdtTrfTxInf/RmtInf/Ustrd',
      isoName: 'Unstructured Remittance',
      mtTag: '70',
      mtName: 'Remittance Information',
      transform: 'splitLines35',
      status: 'transformed',
      notes: 'Single string split into 4×35 char lines. Truncated if > 140 chars.'
    },
    {
      isoPath: 'CdtTrfTxInf/ChrgBr',
      isoName: 'Charge Bearer',
      mtTag: '71A',
      mtName: 'Details of Charges',
      transform: 'chargeBearerReverse',
      status: 'transformed',
      notes: 'SHAR→SHA, DEBT→OUR, CRED→BEN. SLEV has no MT equivalent — defaults to SHA.'
    },
    {
      isoPath: 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/BICFI',
      isoName: 'Intermediary Agent 1 BIC',
      mtTag: '56A',
      mtName: 'Intermediary Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/InstrForCdtrAgt/InstrInf',
      isoName: 'Instruction for Creditor Agent',
      mtTag: '72',
      mtName: 'Sender to Receiver Information',
      transform: 'splitLines35',
      status: 'transformed',
      notes: 'Split to 6×35 lines.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + sender BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: I103 + receiver BIC + priority N' },
    { mtField: ':23B: Bank Operation Code', description: 'Always CRED for MT103' }
  ],

  dataLoss: [
    { isoPath: 'CdtTrfTxInf/PmtId/InstrId', description: 'Instruction ID has no MT equivalent — dropped' },
    { isoPath: 'CdtTrfTxInf/Dbtr/Id/OrgId/LEI', description: 'LEI cannot be represented in MT — dropped' },
    { isoPath: 'CdtTrfTxInf/Cdtr/Id/OrgId/LEI', description: 'LEI cannot be represented in MT — dropped' },
    { isoPath: 'CdtTrfTxInf/Purp/Cd', description: 'Purpose code has no MT field — dropped' },
    { isoPath: 'CdtTrfTxInf/RgltryRptg', description: 'Rich regulatory reporting structure collapsed' },
    { isoPath: 'CdtTrfTxInf/RmtInf/Strd', description: 'Structured remittance cannot map to MT :70: — dropped' },
    { isoPath: 'SplmtryData', description: 'Supplementary data has no MT equivalent — dropped' }
  ],

  valueMaps: {
    chargeBearerReverse: { 'SHAR': 'SHA', 'DEBT': 'OUR', 'CRED': 'BEN', 'SLEV': 'SHA' }
  }
};
