var MAPPING_PACS009_MT202 = {
  mtType: 'MT202',

  fields: [
    {
      isoPath: 'CdtTrfTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      mtTag: '21',
      mtName: 'Related Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO max 35 chars truncated to MT max 16 chars for :21:.'
    },
    {
      isoPath: 'CdtTrfTxInf/IntrBkSttlmAmt',
      isoName: 'Interbank Settlement Amount',
      mtTag: '32A',
      mtName: 'Value Date / Currency / Amount',
      transform: 'buildTag32A',
      status: 'transformed',
      notes: 'Combines IntrBkSttlmDt, Ccy attribute, and value into compound :32A: field.'
    },
    {
      isoPath: 'CdtTrfTxInf/Dbtr/FinInstnId/BICFI',
      isoName: 'Debtor Financial Institution BIC',
      mtTag: '52A',
      mtName: 'Ordering Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/InstgRmbrsmntAgt/FinInstnId/BICFI',
      isoName: 'Instructing Reimbursement Agent BIC',
      mtTag: '53A',
      mtName: 'Sender Correspondent',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/InstdRmbrsmntAgt/FinInstnId/BICFI',
      isoName: 'Instructed Reimbursement Agent BIC',
      mtTag: '54A',
      mtName: 'Receiver Correspondent',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/BICFI',
      isoName: 'Intermediary Agent 1 BIC',
      mtTag: '56A',
      mtName: 'Intermediary Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      mtTag: '57A',
      mtName: 'Account With Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/Cdtr/FinInstnId/BICFI',
      isoName: 'Creditor Financial Institution BIC',
      mtTag: '58A',
      mtName: 'Beneficiary Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'CdtTrfTxInf/InstrForNxtAgt/InstrInf',
      isoName: 'Instruction for Next Agent',
      mtTag: '72',
      mtName: 'Sender to Receiver Information',
      transform: 'splitLines35',
      status: 'transformed',
      notes: 'Split to 6×35 lines.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + sender BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: I202 + receiver BIC + priority N' },
    { mtField: ':20: Transaction Reference', description: 'Generated from MsgId or InstrId' }
  ],

  dataLoss: [
    { isoPath: 'CdtTrfTxInf/PmtId/InstrId', description: 'Instruction ID has no MT equivalent — dropped' },
    { isoPath: 'CdtTrfTxInf/Dbtr/FinInstnId/LEI', description: 'LEI cannot be represented in MT — dropped' },
    { isoPath: 'CdtTrfTxInf/Cdtr/FinInstnId/LEI', description: 'LEI cannot be represented in MT — dropped' },
    { isoPath: 'CdtTrfTxInf/Purp/Cd', description: 'Purpose code has no MT field — dropped' },
    { isoPath: 'SplmtryData', description: 'Supplementary data has no MT equivalent — dropped' }
  ],

  valueMaps: {}
};
