var MAPPING_PAIN001_MT101 = {
  mtType: 'MT101',

  fields: [
    {
      isoPath: 'PmtInf/PmtInfId',
      isoName: 'Payment Information Identification',
      mtTag: '20',
      mtName: 'Sender\'s Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO payment info ID truncated to MT max 16 chars.'
    },
    {
      isoPath: 'PmtInf/ReqdExctnDt/Dt',
      isoName: 'Requested Execution Date',
      mtTag: '30',
      mtName: 'Requested Execution Date',
      transform: 'dateToMT',
      status: 'transformed',
      notes: 'ISO YYYY-MM-DD converted to MT YYMMDD.'
    },
    {
      isoPath: 'PmtInf/DbtrAcct/Id',
      isoName: 'Debtor Account',
      mtTag: '25',
      mtName: 'Authorisation (Account)',
      transform: 'accountIdReverse',
      status: 'clean',
      notes: 'IBAN or proprietary account ID passed through.'
    },
    {
      isoPath: 'PmtInf/CdtTrfTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      mtTag: '21',
      mtName: 'Transaction Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO max 35 chars truncated to MT max 16 chars.'
    },
    {
      isoPath: 'PmtInf/CdtTrfTxInf/Amt/InstdAmt',
      isoName: 'Instructed Amount',
      mtTag: '32B',
      mtName: 'Currency / Transaction Amount',
      transform: 'buildTag32B',
      status: 'transformed',
      notes: 'Ccy attribute + value combined into :32B:. Dot decimal→comma decimal.'
    },
    {
      isoPath: 'PmtInf/Dbtr',
      isoName: 'Debtor',
      mtTag: '50K',
      mtName: 'Ordering Customer',
      transform: 'debtorToParty',
      status: 'transformed',
      notes: 'Structured ISO address collapsed to 4×35 unstructured lines.'
    },
    {
      isoPath: 'PmtInf/CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      mtTag: '57A',
      mtName: 'Account With Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Direct BIC mapping.'
    },
    {
      isoPath: 'PmtInf/CdtTrfTxInf/Cdtr',
      isoName: 'Creditor',
      mtTag: '59',
      mtName: 'Beneficiary Customer',
      transform: 'creditorToParty',
      status: 'transformed',
      notes: 'Structured→unstructured address collapse.'
    },
    {
      isoPath: 'PmtInf/CdtTrfTxInf/RmtInf/Ustrd',
      isoName: 'Unstructured Remittance',
      mtTag: '70',
      mtName: 'Remittance Information',
      transform: 'splitLines35',
      status: 'transformed',
      notes: 'Single string split into 4×35 char lines. Truncated if > 140 chars.'
    },
    {
      isoPath: 'PmtInf/ChrgBr',
      isoName: 'Charge Bearer',
      mtTag: '71A',
      mtName: 'Details of Charges',
      transform: 'chargeBearerReverse',
      status: 'transformed',
      notes: 'SHAR→SHA, DEBT→OUR, CRED→BEN. SLEV defaults to SHA.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + sender BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: I101 + receiver BIC + priority N' },
    { mtField: ':28D: Message Index / Total', description: 'Generated as 1/1 for single payment block' }
  ],

  dataLoss: [
    { isoPath: 'GrpHdr/InitgPty', description: 'Initiating party details beyond name — dropped' },
    { isoPath: 'PmtInf/Dbtr/Id/OrgId/LEI', description: 'LEI cannot be represented in MT — dropped' },
    { isoPath: 'PmtInf/CdtTrfTxInf/Purp/Cd', description: 'Purpose code has no MT field — dropped' },
    { isoPath: 'PmtInf/CdtTrfTxInf/RmtInf/Strd', description: 'Structured remittance cannot map to MT :70: — dropped' },
    { isoPath: 'SplmtryData', description: 'Supplementary data has no MT equivalent — dropped' }
  ],

  valueMaps: {
    chargeBearerReverse: { 'SHAR': 'SHA', 'DEBT': 'OUR', 'CRED': 'BEN', 'SLEV': 'SHA' }
  },

  // Engine metadata
  direction: 'iso-to-mt',
  sourceType: 'pain.001',
  targetType: 'MT101',

  isoRootElement: 'CstmrCdtTrfInitn',
  isoTxPath: 'PmtInf',

  envelope: {
    block1Bic: { from: 'DbtrAgt/FinInstnId/BICFI', fallback: 'CORPUS33XXXX' },
    block2Type: '101',
    block2Bic: { from: 'CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI', fallback: 'CHASUS33XXXX' }
  },

  mtFieldOrder: ['20', '28D', '30', '25', '21', '32B', '50K', '57A', '59', '70', '71A']
};
