var MAPPING_PAIN008_MT104 = {
  mtType: 'MT104',

  fields: [
    {
      isoPath: 'PmtInf/PmtInfId',
      isoName: 'Payment Information Identification',
      mtTag: '20',
      mtName: 'Sender\'s Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO payment info ID truncated to MT max 16 chars.'
    },
    {
      isoPath: 'PmtInf/ReqdColltnDt/Dt',
      isoName: 'Requested Collection Date',
      mtTag: '30',
      mtName: 'Requested Execution Date',
      transform: 'dateToMT',
      status: 'transformed',
      notes: 'ISO YYYY-MM-DD converted to MT YYMMDD. Collection date→execution date.'
    },
    {
      isoPath: 'PmtInf/CdtrAgt/FinInstnId/BICFI',
      isoName: 'Creditor Agent BIC',
      mtTag: '51A',
      mtName: 'Sending Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'Creditor agent maps to sending institution in direct debit context.'
    },
    {
      isoPath: 'PmtInf/Cdtr',
      isoName: 'Creditor',
      mtTag: '50K',
      mtName: 'Ordering Customer (Creditor)',
      transform: 'creditorToParty',
      status: 'transformed',
      notes: 'In direct debit, the creditor is the ordering customer. Structured→unstructured address collapse.'
    },
    {
      isoPath: 'PmtInf/DrctDbtTxInf/PmtId/EndToEndId',
      isoName: 'End to End Identification',
      mtTag: '21',
      mtName: 'Transaction Reference',
      transform: 'truncate16',
      status: 'transformed',
      notes: 'ISO max 35 chars truncated to MT max 16 chars.'
    },
    {
      isoPath: 'PmtInf/DrctDbtTxInf/InstdAmt',
      isoName: 'Instructed Amount',
      mtTag: '32B',
      mtName: 'Currency / Transaction Amount',
      transform: 'buildTag32B',
      status: 'transformed',
      notes: 'Ccy attribute + value combined into :32B:.'
    },
    {
      isoPath: 'PmtInf/DrctDbtTxInf/DbtrAgt/FinInstnId/BICFI',
      isoName: 'Debtor Agent BIC',
      mtTag: '57A',
      mtName: 'Account With Institution',
      transform: 'direct',
      status: 'clean',
      notes: 'In direct debit, debtor agent is the account with institution.'
    },
    {
      isoPath: 'PmtInf/DrctDbtTxInf/Dbtr',
      isoName: 'Debtor',
      mtTag: '59',
      mtName: 'Beneficiary Customer (Debtor)',
      transform: 'debtorToParty',
      status: 'transformed',
      notes: 'In direct debit, the debtor is the "beneficiary" (party being debited). Structured→unstructured.'
    },
    {
      isoPath: 'PmtInf/DrctDbtTxInf/RmtInf/Ustrd',
      isoName: 'Unstructured Remittance',
      mtTag: '70',
      mtName: 'Remittance Information',
      transform: 'splitLines35',
      status: 'transformed',
      notes: 'Single string split into 4×35 char lines.'
    },
    {
      isoPath: 'PmtInf/ChrgBr',
      isoName: 'Charge Bearer',
      mtTag: '71A',
      mtName: 'Details of Charges',
      transform: 'chargeBearerReverse',
      status: 'transformed',
      notes: 'SHAR→SHA, DEBT→OUR, CRED→BEN. SLEV defaults to SHA.'
    }
  ],

  autoGenerated: [
    { mtField: 'Block 1 (Basic Header)', description: 'Generated from context: F01 + sender BIC + session/sequence' },
    { mtField: 'Block 2 (Application Header)', description: 'Generated: I104 + receiver BIC + priority N' },
    { mtField: ':23E: Instruction Code', description: 'Defaults to OTHR' }
  ],

  dataLoss: [
    { isoPath: 'GrpHdr/InitgPty', description: 'Initiating party details beyond name — dropped' },
    { isoPath: 'PmtInf/Cdtr/Id/OrgId/LEI', description: 'LEI cannot be represented in MT — dropped' },
    { isoPath: 'PmtInf/DrctDbtTxInf/DrctDbtTx/MndtRltdInf', description: 'Mandate information has no MT104 equivalent — dropped' },
    { isoPath: 'PmtInf/DrctDbtTxInf/Purp/Cd', description: 'Purpose code has no MT field — dropped' },
    { isoPath: 'PmtInf/DrctDbtTxInf/RmtInf/Strd', description: 'Structured remittance cannot map to MT :70: — dropped' },
    { isoPath: 'SplmtryData', description: 'Supplementary data has no MT equivalent — dropped' }
  ],

  valueMaps: {
    chargeBearerReverse: { 'SHAR': 'SHA', 'DEBT': 'OUR', 'CRED': 'BEN', 'SLEV': 'SHA' }
  },

  // Engine metadata
  direction: 'iso-to-mt',
  sourceType: 'pain.008',
  targetType: 'MT104',

  isoRootElement: 'CstmrDrctDbtInitn',
  isoTxPath: 'PmtInf',

  envelope: {
    block1Bic: { from: 'CdtrAgt/FinInstnId/BICFI', fallback: 'CHASUS33XXXX' },
    block2Type: '104',
    block2Bic: { from: 'DrctDbtTxInf/DbtrAgt/FinInstnId/BICFI', fallback: 'DEUTDEFFXXXX' }
  },

  mtFieldOrder: ['20', '23E', '30', '51A', '50K', '21', '32B', '57A', '59', '70', '71A']
};
